// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// create_cache
void create_cache(Rcpp::String data, Rcpp::String dir);
RcppExport SEXP _rvwgsoc_create_cache(SEXP dataSEXP, SEXP dirSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type dir(dirSEXP);
    create_cache(data, dir);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rvwgsoc_create_cache", (DL_FUNC) &_rvwgsoc_create_cache, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_rvwgsoc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
