# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.create_cache <- function(dir = "", data_file = "", cache_file = "") {
    invisible(.Call(`_rvwgsoc_create_cache`, dir, data_file, cache_file))
}

vwtrain <- function(vwmodel, data_path = "", readable_model = NULL, quiet = FALSE) {
    invisible(.Call(`_rvwgsoc_vwtrain`, vwmodel, data_path, readable_model, quiet))
}

vwtest <- function(vwmodel, data_path = "", probs_path = "", readable_model = NULL, quiet = FALSE) {
    .Call(`_rvwgsoc_vwtest`, vwmodel, data_path, probs_path, readable_model, quiet)
}

